'use client'

import { motion } from 'framer-motion'
import { ArrowUpRight, MapPin, Phone, MessageCircle, Dumbbell, HeartPulse, Users, Sparkles, Zap, ShieldCheck, ChevronRight } from 'lucide-react'

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=85`

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <motion.div className={className} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: .6 }}>{children}</motion.div>
}

export function Nav() {
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-border/50 bg-background/85 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="#top" className="font-heading text-2xl tracking-wide text-foreground">GLOBAL<span className="text-primary">.</span></a><nav className="hidden items-center gap-6 lg:flex">{['About','Services','Gallery','Trainers','Pricing','Contact'].map(x => <a key={x} href={`#${x.toLowerCase()}`} className="text-xs font-bold uppercase tracking-widest text-muted-foreground transition-colors hover:text-primary">{x}</a>)}<a href="#contact" className="bg-primary px-5 py-3 text-xs font-black uppercase tracking-widest text-primary-foreground transition-transform hover:-translate-y-0.5">Start Free Trial</a></nav><a href="#contact" aria-label="Start free trial" className="bg-primary px-3 py-2 text-xs font-black uppercase text-primary-foreground lg:hidden">Trial</a></div></header>
}

export function Hero() { return <section id="top" className="relative flex min-h-screen items-end overflow-hidden"><img className="absolute inset-0 h-full w-full object-cover opacity-45" src={img('photo-1534438327276-14e5300c3a48')} alt="Moody gym interior with weight racks" /><div className="absolute inset-0 bg-gradient-to-t from-background via-background/65 to-background/10" /><div className="relative mx-auto w-full max-w-7xl px-5 pb-20 pt-36 lg:px-8 lg:pb-28"><Reveal><p className="mb-5 flex items-center gap-3 font-mono text-xs font-bold uppercase tracking-[.3em] text-primary"><span className="h-px w-10 bg-primary" /> Ghatkopar, Mumbai</p><h1 className="max-w-4xl font-heading text-[clamp(4.5rem,13vw,10.5rem)] leading-[.8] tracking-tight text-foreground">SERIOUSLY<br /><span className="text-primary">FUN</span> FITNESS</h1><p className="mt-8 max-w-md text-base leading-7 text-muted-foreground">A high-energy training floor built for real people, real progress, and a community that makes showing up the best part.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#contact" className="inline-flex items-center gap-2 bg-primary px-6 py-4 text-sm font-black uppercase tracking-wider text-primary-foreground transition-transform hover:-translate-y-1">Start Free Trial <ArrowUpRight size={17} /></a><a href="#services" className="inline-flex items-center gap-2 border border-foreground/40 px-6 py-4 text-sm font-black uppercase tracking-wider text-foreground hover:border-primary hover:text-primary">Explore Programs</a></div></Reveal></div><div className="absolute bottom-0 right-0 hidden h-20 w-2/5 -skew-x-[25deg] translate-x-1/4 bg-primary lg:block" /></section> }

export function About() { return <section id="about" className="relative overflow-hidden bg-surface py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><Reveal><div className="relative"><img className="h-[430px] w-full object-cover grayscale" src={img('photo-1581009146145-b5ef050c2e1e')} alt="Athlete training with a barbell" /><div className="absolute -bottom-4 -right-4 bg-primary p-5 font-heading text-4xl leading-none text-primary-foreground">NO<br />EXCUSES.</div></div></Reveal><Reveal><p className="eyebrow">THE GLOBAL WAY</p><h2 className="section-title mt-4">TRAIN HARD.<br /><span className="text-primary">LIVE LOUD.</span></h2><p className="mt-7 max-w-lg text-muted-foreground leading-7">Global Gym is more than a place to lift. We built a seriously fun training community where big energy meets smart programming, and every member has a reason to come back tomorrow.</p><p className="mt-4 max-w-lg text-muted-foreground leading-7">No intimidation. No ego. Just good people, great coaching, and the kind of results you can feel.</p><a href="#services" className="mt-8 inline-flex items-center gap-2 font-bold uppercase tracking-widest text-primary">What we do <ChevronRight size={17} /></a></Reveal></div></section> }

const services = [[Dumbbell,'Strength Training','Machines, free weights, and a plan that gets you stronger.'],[HeartPulse,'Cardio','Build your engine with treadmills, cycles, and high-intensity conditioning.'],[Users,'Group Classes','Big energy, loud music, zero judgement. Find your people.'],[ShieldCheck,'Personal Training','One-on-one coaching that makes every rep count.'],[Zap,'Zumba','Dance, sweat, and forget you are working out.'],[Sparkles,'Spa & Recovery','Reset hard with recovery zones built for your next session.']]
export function Services() { return <section id="services" className="py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><p className="eyebrow">THE PLAYBOOK</p><h2 className="section-title mt-4">EVERY WAY<br /><span className="text-primary">TO MOVE.</span></h2></Reveal><div className="mt-14 grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-3">{services.map(([Icon,title,desc],i) => <Reveal key={title}><article className="group min-h-60 bg-background p-7 transition-colors hover:bg-surface"><div className="mb-12 flex items-start justify-between"><Icon className="text-primary" size={29} strokeWidth={1.5} /><span className="font-mono text-xs text-muted-foreground">0{i+1}</span></div><h3 className="font-heading text-3xl tracking-wide text-foreground">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{desc as string}</p></article></Reveal>)}</div></div></section> }

const gallery = ['photo-1534438327276-14e5300c3a48','photo-1571019613454-1cb2f99b2d8b','photo-1583454110551-21f2fa2afe61','photo-1517836357463-d25dfeac3438','photo-1581009146145-b5ef050c2e1e','photo-1546483875-ad9014c88eba']
export function Gallery() { return <section id="gallery" className="bg-surface py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><div className="flex items-end justify-between"><div><p className="eyebrow">THE FLOOR</p><h2 className="section-title mt-4">SEE YOU<br /><span className="text-primary">INSIDE.</span></h2></div><span className="hidden font-mono text-xs uppercase tracking-widest text-muted-foreground sm:block">Scroll / Sweat / Repeat</span></div></Reveal><div className="mt-14 grid grid-cols-2 gap-3 md:grid-cols-3">{gallery.map((id,i) => <Reveal key={id} className={i===0 || i===5 ? 'col-span-2' : ''}><img className={`w-full object-cover grayscale transition-all duration-500 hover:grayscale-0 ${i===0 || i===5 ? 'h-72 md:h-96' : 'h-56 md:h-72'}`} src={img(id)} alt={`Global Gym training space ${i+1}`} /></Reveal>)}</div></div></section> }

const trainers = [['Vineet Mankani','Strength & Conditioning','photo-1567013127542-490d757e51fc'],['Anaya Shah','Functional Training','photo-1594381898411-846e7d193883'],['Vikram Singh','Performance Coach','photo-1534438327276-14e5300c3a48'],['Nisha Patil','Zumba & Mobility','photo-1549476464-37392f717541']]
export function Trainers() { return <section id="trainers" className="py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><p className="eyebrow">THE CREW</p><h2 className="section-title mt-4">MEET YOUR<br /><span className="text-primary">COACHES.</span></h2></Reveal><div className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{trainers.map(([name,specialty,id]) => <Reveal key={name}><article><img className="aspect-[4/5] w-full object-cover grayscale" src={img(id)} alt={`${name}, ${specialty}`} /><h3 className="mt-5 font-heading text-2xl tracking-wide">{name}</h3><p className="mt-1 font-mono text-[10px] font-bold uppercase tracking-widest text-primary">{specialty}</p></article></Reveal>)}</div></div></section> }

const plans = [['BASIC','₹1,499','For the self-starter',['Full gym access','Locker room access','Open training floor']],['PRO','₹2,499','For the committed',['Everything in Basic','All group classes','Monthly body assessment','Guest pass every month']],['ELITE','₹3,999','For the all-in',['Everything in Pro','4 PT sessions / month','Spa & recovery access','Nutrition consultation']]]
export function Pricing() { return <section id="pricing" className="bg-surface py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><p className="eyebrow">MEMBERSHIPS</p><h2 className="section-title mt-4">PICK YOUR<br /><span className="text-primary">LEVEL.</span></h2></Reveal><div className="mt-14 grid gap-4 lg:grid-cols-3">{plans.map(([name,price,desc,features],i) => <Reveal key={name}><article className={`relative border p-7 ${i===1 ? 'border-primary bg-background' : 'border-border'}`}>{i===1 && <span className="absolute right-5 top-0 -translate-y-1/2 bg-primary px-3 py-1 font-mono text-[10px] font-bold uppercase tracking-widest text-primary-foreground">Most Popular</span>}<p className="font-mono text-xs font-bold tracking-widest text-primary">{name}</p><p className="mt-8 font-heading text-6xl">{price}</p><p className="mt-2 text-sm text-muted-foreground">{desc}</p><ul className="mt-8 space-y-3 border-t border-border pt-6">{(features as string[]).map(f=><li key={f} className="flex gap-2 text-sm text-muted-foreground"><span className="text-primary">+</span>{f}</li>)}</ul><a href="#contact" className={`mt-8 block py-4 text-center text-xs font-black uppercase tracking-widest ${i===1 ? 'bg-primary text-primary-foreground' : 'border border-foreground/30 text-foreground hover:border-primary hover:text-primary'}`}>Choose {name}</a></article></Reveal>)}</div></div></section> }

export function Testimonials() { return <section className="py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal><p className="eyebrow">MEMBER ENERGY</p><h2 className="section-title mt-4">GOOD VIBES.<br /><span className="text-primary">REAL RESULTS.</span></h2></Reveal><div className="mt-14 grid gap-4 md:grid-cols-3">{[['“Finally, a gym where I actually look forward to showing up. The coaches remember your name and your goals.”','PRIYA K.'],['“The group classes are absolute fire. I have more energy, more confidence, and my jeans fit better.”','ARJUN R.'],['“Global feels like a community, not a membership. Best training decision I have made in Mumbai.”','MEERA S.']].map(([quote,name])=><Reveal key={name}><blockquote className="border-l-2 border-primary bg-surface p-7"><p className="text-lg leading-8 text-foreground">{quote}</p><footer className="mt-8 font-mono text-[10px] font-bold tracking-widest text-primary">— {name}</footer></blockquote></Reveal>)}</div></div></section> }

export function CTA() { return <section id="contact" className="relative overflow-hidden bg-primary py-20 text-primary-foreground lg:py-28"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 lg:flex-row lg:items-end lg:justify-between lg:px-8"><Reveal><p className="font-mono text-xs font-bold uppercase tracking-[.3em] opacity-75">YOUR NEXT REP STARTS HERE</p><h2 className="mt-4 max-w-3xl font-heading text-6xl leading-[.85] tracking-tight lg:text-8xl">READY TO HAVE<br />SOME FUN?</h2></Reveal><a href="tel:+919876543210" className="inline-flex w-fit items-center gap-3 border border-primary-foreground/50 px-6 py-4 text-sm font-black uppercase tracking-wider hover:bg-primary-foreground hover:text-primary"><MessageCircle size={18} /> Book a free trial</a></div></section> }

export function Footer() { return <footer className="bg-background py-14"><div className="mx-auto grid max-w-7xl gap-12 px-5 md:grid-cols-3 lg:px-8"><div><a href="#top" className="font-heading text-3xl">GLOBAL<span className="text-primary">.</span></a><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">Seriously fun fitness for Ghatkopar. Come for the workout, stay for the crew.</p><div className="mt-6 flex gap-4"><a href="#" aria-label="Instagram" className="font-mono text-xs font-bold uppercase tracking-widest hover:text-primary">IG</a><a href="#" aria-label="Facebook" className="font-mono text-xs font-bold uppercase tracking-widest hover:text-primary">FB</a></div></div><div><p className="eyebrow">FIND US</p><p className="mt-4 flex gap-3 text-sm leading-6 text-muted-foreground"><MapPin size={18} className="shrink-0 text-primary" /> 2nd Floor, R City Mall Road,<br />Ghatkopar West, Mumbai 400086</p><p className="mt-4 flex gap-3 text-sm text-muted-foreground"><Phone size={16} className="text-primary" /> +91 98765 43210</p></div><div><p className="eyebrow">QUICK LINKS</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm text-muted-foreground">{['About','Services','Gallery','Trainers','Pricing','Contact'].map(x=><a key={x} href={`#${x.toLowerCase()}`} className="hover:text-primary">{x}</a>)}</div></div></div><div className="mx-auto mt-14 max-w-7xl border-t border-border px-5 pt-5 font-mono text-[10px] uppercase tracking-widest text-muted-foreground lg:px-8">© 2025 Global Gym Ghatkopar · Built to move</div></footer> }
